### ISSUE TITLE
minimal required matlab version? (Name-Value unsuppored in 2020)

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_SerialDevice#1]
I just noted that you used the [Name-Value convention](https://www.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html#mw_1b62b6d6-a445-4c55-a9b9-9c70becfdbe6) for validating function arguments, which is not supported by Matlab 2020a (on my development machine) nor 2020b (stock installation on LAST machines).
Are there other features of recent matlab which you used extensively? (e.g. we mentioned the Variable Store)
To change Name-Value to the former syntax would be probably still practicable at this point; but when will you force us to transition to a more recent version? Which?

```
>> version

ans =

    '9.9.0.1467703 (R2020b)'

>> inst.SerialDevice
Error using inst.SerialDevice
Error: File:
/home/ocs/matlab/LAST/LAST_SerialDevice/+inst/@SerialDevice/SerialDevice.m
Line: 67 Column: 25
Incorrect use of '=' operator. To assign a value to a variable, use '='. To
compare values for equality, use '=='.
```

**Comment by blumzi** [comment]
To quote from .../matlab/LAST/LAST_SerialDevice/+inst/@SerialDevice/SerialDevice.m

            if isMATLABReleaseOlderThan("R2022a")
                throw(MException("OCS:SerialDevice:MatlabRelease", "This class works on release R2022a or newer (not %s)", matlabRelease.Release))
            end

If you need a license for 2022a for any machine, I think I know how to get one.

**Comment by EastEriq** [comment]
Maybe there is a bug on that? Because as you see from the transcript above, a syntax error is thrown, not that exception.

**Comment by blumzi** [comment]
I pushed a version that runs long enough on 2020b to say it needs at least
2022a
