### ISSUE TITLE
`SerialDevice(Logging=true)` not effected at creation?

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_SerialDevice#11]
I'm calling `X.SerialResource=inst.SerialDevice(Port, ...  ,  Logging = true)`, and I see no logging in `/var/log/ocs/SerialDevice-_dev_ttyS4.txt`, only lines like
```
[160063] 2022-11-13 08:33:57.978 > =========================================== Started
```
Logging does turn on if afterwards I set it using the setter, i.e. `X.SerialResource.Logging=true`.

Timing in my use case does not seem to be impacted much by logging:
```
>> X.SerialResource.Logging=true; tic;X.MotorHA,toc

ans =

      -66.917

Elapsed time is 0.115953 seconds.
>> X.SerialResource.Logging=false; tic;X.MotorHA,toc

ans =

      -66.917

Elapsed time is 0.109853 seconds.
>>
```
(the typical jitter in these timings is always several ms, more than the difference in these two particular calls)

**Comment by blumzi** [comment]
It now uses the Logging value at creation time

**Comment by EastEriq** [comment]
Did you push it? I see no new commit since 26 days.
