### ISSUE TITLE
`.connect` hangs for nonexistent ports, or for ports connected to a non responding instrument

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_SerialDevice#3]
```
>> i=inst.SerialDevice('/dev/ttyUSB0') % USB0 not on system

i = 

  SerialDevice with properties:

    Connected: 0
       Logger: [1×1 MsgLogger]

>> i.connect % hanging till Crtl-c
Operation terminated by user during inst.SerialDevice/directive


In inst.SerialDevice/connect (line 146)
            response = Obj.directive('connected', true);
```
`/var/log/ocs/SerialDevice-_dev_ttyUSB0.txt` fills with
```
[2054238] 2022-10-18 12:05:02.898 > [DBG] [upper] SerialDevice.directive: : waiting for response to directive('connected'='true')
[2054238] 2022-10-18 12:05:03.906 > [DBG] [upper] SerialDevice.directive: : waiting for response to directive('connected'='true')
[2054238] 2022-10-18 12:05:04.908 > [DBG] [upper] SerialDevice.directive: : waiting for response to directive('connected'='true')
[2054238] 2022-10-18 12:05:05.910 > [DBG] [upper] SerialDevice.directive: : waiting for response to directive('connected'='true')
```
Instead of retrying forever, `.connect` should return after a reasonably short timeout. Consider that there are many reasons for failure: absence of a response may be either because of an invalid `.PortPath`, or because of a busy (otherwise) serial resource, or because of wrong serial communication settings, or because of a wrong `.StatusCommand` definition.

**Comment by EastEriq** [comment]
I the constructor of `SerialDevice`, I see room for an argument `Timeout`, with no default value, which I think is unused in the code.
There is btw also an `Args.Interval`, but at line [142](https://github.com/blumzi/LAST_SerialDevice/blob/dbb15c3273a86b5abb641becc6463f787c005eca/%2Binst/%40SerialDevice/SerialDevice.m#L142) the hardwired value of 5 is used.

**Comment by EastEriq** [comment]
Ah ok, now I see, these arguments are passed verbatim as WorkerArgs

**Comment by blumzi** [comment]
Existence of the requested serial port was moved to the upper part of the driver
