### ISSUE TITLE
what if the parallel pool ceases to exist?

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_SerialDevice#4]
So I defined a SerialDevice object, turned to something else in the meantime, and went back to matlab after the canonical 30 min of survival of the parallel pool expired. Now attempts to access some property of it hang.
```
>> i.WorkerArgs.Timeout=seconds(5)

i = 
```
Only after Ctrl-c I get
```
  SerialDevice with properties:

    Connected: 0
       Logger: [1×1 MsgLogger]
```
The log adds lines of
```
[2054238] 2022-10-18 12:49:54.038 > [DBG] [upper] The worker's job is not valid, cannot send directive
[2054238] 2022-10-18 12:53:30.451 > [DBG] [upper] The worker's job is not valid, cannot send directive
[2054238] 2022-10-18 12:53:30.463 > [DBG] [upper] The worker's job is not valid, cannot send directive
```

I think that nonexistence of the pool should be trapped (and the pool restarted). In our use case it is quite possible that commands are sent very infrequently (think for example at focus). Ok by session default one could perhaps make `parpool.IdleTimeout` much longer but I still think that the situation should instead be trapped.

**Comment by blumzi** [comment]
A timer checks if the job is still alive, if not it will disconnect and re-connect (maybe needs more testing)
